---
common-steps:
  - &install_build_dependencies
    run:
      name: Install build dependencies
      command: |
        set -e
        apt-get update && apt-get install --yes git make sudo

  - &install_packaging_dependencies
    run:
      name: Install Debian packaging dependencies and download Python wheels
      command: |
        set -x
        mkdir ~/packaging && cd ~/packaging
        # local builds may not have an ssh url, so || true
        git config --global --unset url.ssh://git@github.com.insteadof || true
        git clone https://github.com/freedomofpress/securedrop-builder.git
        cd securedrop-builder
        apt-get update && apt-get install -y sudo make
        make install-deps
        source .venv/bin/activate
        PKG_DIR=~/project make requirements

  - &verify_requirements
    run:
      name: Ensure that build-requirements.txt and requirements.txt are in sync.
      command: |
        cd ~/project
        # Return 1 if unstaged changes exist (after `make requirements` in the
        # previous run step), else return 0.
        git diff --quiet

  - &build_debian_package
    run:
      name: Build debian package
      command: |
        cd ~/packaging/securedrop-builder
        export PKG_VERSION=1000.0
        export PKG_PATH=~/project/
        source .venv/bin/activate
        make securedrop-proxy

version: 2.1

jobs:
  build:
    parameters: &parameters
      image:
        type: string
    docker: &docker
      - image: debian:<< parameters.image >>
    steps:
      - checkout
      - *install_build_dependencies
      - *install_packaging_dependencies
      - *verify_requirements
      - *build_debian_package


workflows:
  securedrop_proxy_ci:
    jobs: &jobs
      - build:
          matrix: &matrix
            parameters:
              image:
                - bullseye
                - bookworm

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs: *jobs
