version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5-stretch
    steps:
      - checkout

      - run:
          name: Install Debian packaging dependencies and download wheels
          command: |
            mkdir ~/packaging && cd ~/packaging
            git clone https://github.com/freedomofpress/securedrop-debian-packaging.git
            cd securedrop-debian-packaging
            make install-deps && make fetch-wheels
      - run:
          name: Tag and make source tarball
          command: |
            cd ~/project
            git tag 1000.0  # Dummy version number, doesn't matter what we put here
            python3 setup.py sdist

      - run:
          name: Build debian package
          command: |
            cd ~/packaging/securedrop-debian-packaging
            export PKG_VERSION=1000.0
            export PKG_PATH=~/packaging/securedrop-proxy/dist/securedrop-proxy-$PKG_VERSION.tar.gz
            make securedrop-proxy

  test:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout

      - run:
          name: Install requirements and run tests
          command: |
            virtualenv .venv
            source .venv/bin/activate
            pip install --require-hashes -r dev-requirements.txt
            make test

      - run:
          name: Check Python dependencies for CVEs
          command: |
            set -e
            source .venv/bin/activate
            make safety

workflows:
  version: 2
  securedrop_proxy_ci:
    jobs:
      - test
      - build
