---
common-steps:
  - &install_testing_dependencies
    run:
      name: Install testing dependencies
      command: |
        set -e
        apt update && apt install -y git gnupg make python3-dev gnupg python3-venv libnotify-bin
  - &install_build_dependencies
    run:
      name: Install build dependencies
      command: |
        set -e
        apt update && apt install -y git make sudo
  - &run_unit_tests
    run:
      name: Install requirements and run unit tests
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make test
  - &run_lint
    run:
      name: Run lint, type checking, code formatting
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make lint mypy
  - &check_security
    run:
      name: Run static analysis on source code to find security issues
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make bandit
  - &check_python_dependencies_for_vulnerabilities
    run:
      name: Check Python dependencies for known vulnerabilities
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make safety
  - &install_packaging_dependencies
    run:
      name: Install Debian packaging dependencies and download Python wheels
      command: |
        set -x
        mkdir ~/packaging && cd ~/packaging
        # local builds may not have an ssh url, so || true
        git config --global --unset url.ssh://git@github.com.insteadof || true
        git clone https://github.com/freedomofpress/securedrop-debian-packaging.git
        cd securedrop-debian-packaging
        apt-get update && apt-get install -y sudo make
        make install-deps
        PKG_DIR=~/project make requirements
  - &check_packaging_requirements
    run:
      name: Ensure that the same Python requirements are used for packaging and production.
      command: |
        cd ~/project
        # Fail if unstaged changes exist (after `make requirements` in the previous run step).
        git diff --ignore-matching-lines=# --exit-code
  - &check_testing_requirements
    run:
      name: Ensure that the same Python requirements are used for development/testing and production.
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make requirements
        git diff --ignore-matching-lines=# --exit-code
  - &build_debian_package
    run:
      name: Build debian package
      command: |
        cd ~/packaging/securedrop-debian-packaging
        export PKG_VERSION=1000.0
        export PKG_PATH=~/project/
        make securedrop-proxy
version: 2.1

jobs:
  build:
    parameters: &parameters
      image:
        type: string
    docker: &docker
      - image: debian:<< parameters.image >>
    steps:
      - *install_build_dependencies
      - checkout
      - *install_packaging_dependencies
      - *check_packaging_requirements
      - *build_debian_package

  unit-test:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *run_unit_tests
      - store_test_results:
          path: test-results

  lint:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *run_lint

  check-security:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *check_security

  check-python-security:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *check_python_dependencies_for_vulnerabilities

  check-testing-requirements:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *check_testing_requirements

workflows:
  securedrop_export_ci:
    jobs: &jobs
      - unit-test:
          matrix: &matrix
            parameters:
              image:
                - bullseye
                - bookworm
      - lint:
          matrix: *matrix
      - check-testing-requirements:
          matrix: *matrix
      - check-security:
          matrix: *matrix
      - check-python-security:
          matrix: *matrix
      - build:
          matrix: *matrix

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs: *jobs
