---
common-steps:
  - &base
    run:
      name: Install base requirements
      command: |
        apt-get update && apt-get install -y git make python3-dev python3-venv

  - &run_tests
    run:
      name: Install requirements and run tests
      command: |
        make venv
        source .venv/bin/activate
        make check

  - &install_packaging_dependencies
    run:
      name: Install Debian packaging dependencies and download wheels
      command: |
        mkdir ~/packaging && cd ~/packaging
        git config --global --unset url.ssh://git@github.com.insteadof
        git clone https://github.com/freedomofpress/securedrop-debian-packaging.git
        cd securedrop-debian-packaging
        make install-deps
        PKG_DIR=~/project make requirements

  - &verify_requirements
    run:
      name: Ensure that build-requirements.txt and requirements.txt are in sync.
      command: |
        cd ~/project
        # Return 1 if unstaged changes exist (after `make requirements` in the
        # previous run step), else return 0.
        git diff --quiet

  - &make_source_tarball
    run:
      name: Tag and make source tarball
      command: |
        cd ~/project
        ./update_version.sh 1000.0  # Dummy version number, doesn't matter what we put here
        python3 setup.py sdist

  - &build_debian_package
    run:
      name: Build debian package
      command: |
        cd ~/packaging/securedrop-debian-packaging
        export PKG_VERSION=1000.0
        export PKG_PATH=/home/circleci/project/dist/securedrop-proxy-$PKG_VERSION.tar.gz
        make securedrop-proxy

version: 2
jobs:
  build-bullseye:
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - *base
      - *install_packaging_dependencies
      - *verify_requirements
      - *make_source_tarball
      - *build_debian_package

  test-bullseye:
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - *base
      - *run_tests

  build-bookworm:
    docker:
      - image: debian:bookworm
    steps:
      - checkout
      - *base
      - *install_packaging_dependencies
      - *verify_requirements
      - *make_source_tarball
      - *build_debian_package

  test-bookworm:
    docker:
      - image: debian:bookworm
    steps:
      - checkout
      - *base
      - *run_tests


workflows:
  version: 2
  securedrop_proxy_ci:
    jobs:
      - test-bullseye
      - build-bullseye
      - test-bookworm
      - build-bookworm

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test-bullseye
      - build-bullseye
      - test-bookworm
      - build-bookworm
